/**
 * Generates the BaseDomain abstract class for shared CRUD logic
 *
 * This generates a base class that provides common hook orchestration,
 * reducing boilerplate in individual domain files.
 */
export class BaseDomainGenerator {
  /**
   * Generate the base domain file content
   */
  generate(): string {
    return `/**
 * Base Domain Class
 *
 * Provides shared CRUD operations with hook orchestration.
 * Model-specific domains extend this class.
 *
 * Generated by COG - Do not modify manually
 */

import { eq, desc, asc, sql, type AnyColumn } from 'drizzle-orm';
import { type PgTable } from 'drizzle-orm/pg-core';
import { type ZodSchema } from 'zod';
import { InvalidFilterException, NotFoundException } from './exceptions.ts';
import { withoutTransaction, runAfterCommit, type DbTransaction } from '../db/database.ts';
import { DomainHooks, DomainHookContext, QueryOptions } from './hooks.types.ts';
import { buildWhereSQL, isWhereFilter, stripUnexposedFields, stripUnacceptedFields, validateFilter, type SQL, type FieldMeta } from '../utils/filter.utils.ts';
import { getExposedFields, getCreateUnexposedFields, getReadUnexposedFields, getCreateUnacceptedFields, getUpdateUnacceptedFields } from '../utils/field-meta.utils.ts';

// ============================================
// Types
// ============================================

/**
 * Configuration for a domain class
 */
export interface DomainConfig<T, TNew> {
  /** The Drizzle table */
  table: PgTable;
  /** Zod schema for insert validation */
  insertSchema: ZodSchema<TNew>;
  /** Zod schema for update validation */
  updateSchema: ZodSchema<Partial<TNew>>;
  /** Field metadata map */
  fieldMeta: Map<string, FieldMeta>;
  /** Model name for error messages */
  modelName: string;
  /** Whether the model has timestamps */
  hasTimestamps: boolean;
  /** Primary key field name (default: 'id') */
  primaryKey?: string;
}

/**
 * Derived field arrays from metadata
 */
interface DerivedFields {
  exposedFields: Set<string>;
  createUnexposedFields: string[];
  readUnexposedFields: string[];
  createUnacceptedFields: string[];
  updateUnacceptedFields: string[];
}

// ============================================
// Base Domain Class
// ============================================

/**
 * Abstract base class for domain operations
 *
 * Provides common CRUD logic with hook orchestration.
 * Subclasses must implement relationship loading (includes).
 */
export abstract class BaseDomain<
  T extends Record<string, unknown>,
  TNew,
  DomainEnvVars extends Record<string, unknown> = Record<string, unknown>
> {
  protected config: DomainConfig<T, TNew>;
  protected hooks: DomainHooks<T, TNew, Partial<TNew>, DomainEnvVars>;
  protected fields: DerivedFields;

  constructor(
    config: DomainConfig<T, TNew>,
    hooks?: DomainHooks<T, TNew, Partial<TNew>, DomainEnvVars>,
  ) {
    this.config = config;
    this.hooks = hooks || {};
    this.fields = {
      exposedFields: getExposedFields(config.fieldMeta),
      createUnexposedFields: getCreateUnexposedFields(config.fieldMeta),
      readUnexposedFields: getReadUnexposedFields(config.fieldMeta),
      createUnacceptedFields: getCreateUnacceptedFields(config.fieldMeta),
      updateUnacceptedFields: getUpdateUnacceptedFields(config.fieldMeta),
    };
  }

  /**
   * Get the primary key field name
   */
  protected get primaryKey(): string {
    return this.config.primaryKey || 'id';
  }

  /**
   * Get primary key column from table
   */
  protected get pkColumn(): AnyColumn {
    return (this.config.table as unknown as Record<string, AnyColumn>)[this.primaryKey];
  }

  // ============================================
  // Abstract methods for model-specific logic
  // ============================================

  /**
   * Load relationships for a single result (findById)
   * Override in subclass to handle relationship includes; pass the context on to the related domains
   */
  protected abstract loadRelationshipsForOne(
    result: T,
    options: QueryOptions,
    tx?: DbTransaction,
    context?: DomainHookContext<DomainEnvVars>,
  ): Promise<T>;

  /**
   * Load relationships for multiple results (findMany)
   * Override in subclass to handle relationship includes
   */
  protected abstract loadRelationshipsForMany(
    results: T[],
    options: QueryOptions,
    tx?: DbTransaction,
    context?: DomainHookContext<DomainEnvVars>,
  ): Promise<T[]>;

  // ============================================
  // CRUD Operations
  // ============================================

  /**
   * Create a new record
   */
  async create(
    input: TNew,
    tx: DbTransaction,
    options?: QueryOptions,
    context?: DomainHookContext<DomainEnvVars>,
  ): Promise<T> {
    // Strip unaccepted fields from input (before any hooks)
    const strippedInput = stripUnacceptedFields(
      input as unknown as Record<string, unknown>,
      this.fields.createUnacceptedFields,
    );

    // Before-create hook (outside transaction, before validation)
    let transformedInput: unknown = strippedInput;
    if (this.hooks.beforeCreate) {
      transformedInput = await this.hooks.beforeCreate(strippedInput, context);
    }

    // Validate input before pre-hook
    const validatedInput = this.config.insertSchema.parse(transformedInput) as TNew;

    // Pre-create hook (within transaction)
    let processedInput = validatedInput;
    if (this.hooks.preCreate) {
      processedInput = await this.hooks.preCreate(validatedInput, input, tx, context);
      // Validate pre-hook output
      processedInput = this.config.insertSchema.parse(processedInput) as TNew;
    }

    // Perform create operation
    const [created] = await tx
      .insert(this.config.table)
      .values(processedInput as Record<string, unknown>)
      .returning() as T[];

    // Post-create hook (within transaction)
    let result = created;
    if (this.hooks.postCreate) {
      result = await this.hooks.postCreate(processedInput, created, input, tx, context);
    }

    // Sanitize response (strip unexposed fields) unless skipped
    if (!options?.skipSanitization) {
      result = stripUnexposedFields(result, this.fields.createUnexposedFields) as T;
    }

    // After-create hook: starts once the transaction has committed, receives what the caller gets
    if (this.hooks.afterCreate) {
      const afterCreate = this.hooks.afterCreate;
      runAfterCommit(tx, () => afterCreate(result, input, context));
    }

    return result;
  }

  /**
   * Find record by ID
   */
  async findById(
    id: string,
    tx?: DbTransaction,
    options?: QueryOptions,
    context?: DomainHookContext<DomainEnvVars>,
  ): Promise<T | null> {
    // Before-find-by-id hook (outside transaction)
    if (this.hooks.beforeFindById) {
      id = await this.hooks.beforeFindById(id, context);
    }

    const db = tx || withoutTransaction();

    // Pre-find hook
    if (this.hooks.preFindById) {
      const preResult = await this.hooks.preFindById(id, tx, context);
      id = preResult.id;
    }

    // Build and execute query
    const result = await db
      .select()
      .from(this.config.table)
      .where(eq(this.pkColumn, id));

    let found = (result[0] as T) || null;

    // Load relationships if requested
    if (options?.include && options.include.length > 0 && found) {
      found = await this.loadRelationshipsForOne(found, options, tx, context);
    }

    // Post-find hook
    let finalResult: T | null = found;
    if (this.hooks.postFindById && found !== null) {
      finalResult = await this.hooks.postFindById(id, found, tx, context);
    }

    // Sanitize response unless skipped
    if (finalResult && !options?.skipSanitization) {
      finalResult = stripUnexposedFields(finalResult, this.fields.readUnexposedFields) as T;
    }

    // After-find hook: starts once the transaction has committed, right away without one
    if (this.hooks.afterFindById) {
      const afterFindById = this.hooks.afterFindById;
      runAfterCommit(tx, () => afterFindById(finalResult, context));
    }

    return finalResult;
  }

  /**
   * Find all records with pagination and filtering
   */
  async findMany(
    tx?: DbTransaction,
    options: QueryOptions = {},
    context?: DomainHookContext<DomainEnvVars>,
  ): Promise<{ data: T[]; total: number }> {
    // Convert WhereFilter to SQL first (so hooks receive SQL). A condition that cannot be applied is
    // refused: dropping it would widen the result.
    if (options.where && isWhereFilter(options.where)) {
      const validation = validateFilter(options.where, this.config.fieldMeta);
      if (!validation.valid) {
        throw new InvalidFilterException(validation.error ?? 'Invalid filter');
      }
      options = {
        ...options,
        where: buildWhereSQL(options.where, this.config.table, this.fields.exposedFields),
      };
    }

    // Before-find-many hook (outside transaction, receives SQL)
    if (this.hooks.beforeFindMany) {
      options = await this.hooks.beforeFindMany(options, context);
    }

    const db = tx || withoutTransaction();

    // Pre-find hook
    if (this.hooks.preFindMany) {
      options = await this.hooks.preFindMany(tx, options, context);
    }

    const whereSQL = options.where as SQL | undefined;

    // Build query
    let baseQuery = db.select().from(this.config.table);

    if (whereSQL) {
      baseQuery = baseQuery.where(whereSQL) as unknown as typeof baseQuery;
    }

    if (options.orderBy) {
      const orderFn = options.orderDirection === 'desc' ? desc : asc;
      const column = (this.config.table as unknown as Record<string, AnyColumn>)[options.orderBy];
      if (column) {
        baseQuery = baseQuery.orderBy(orderFn(column)) as unknown as typeof baseQuery;
      }
    }

    if (options.limit) {
      baseQuery = baseQuery.limit(options.limit) as unknown as typeof baseQuery;
    }

    if (options.offset) {
      baseQuery = baseQuery.offset(options.offset) as unknown as typeof baseQuery;
    }

    // Execute query
    let results = (await baseQuery) as T[];

    // Load relationships if requested
    if (options?.include && options.include.length > 0 && results.length > 0) {
      results = await this.loadRelationshipsForMany(results, options, tx, context);
    }

    // Get total count
    const countQueryBase = db
      .select({ count: sql<number>\`count(*)\` })
      .from(this.config.table);

    const countQuery = whereSQL
      ? countQueryBase.where(whereSQL)
      : countQueryBase;

    const [{ count }] = await countQuery;

    // Post-find hook
    let finalResults = this.hooks.postFindMany
      ? await this.hooks.postFindMany(options, results, tx, context)
      : results;

    // Sanitize response unless skipped
    if (!options.skipSanitization) {
      finalResults = stripUnexposedFields(finalResults, this.fields.readUnexposedFields) as T[];
    }

    // After-find hook: starts once the transaction has committed, right away without one
    if (this.hooks.afterFindMany) {
      const afterFindMany = this.hooks.afterFindMany;
      runAfterCommit(tx, () => afterFindMany(finalResults, context));
    }

    return {
      data: finalResults,
      total: Number(count),
    };
  }

  /**
   * Update a record
   */
  async update(
    id: string,
    input: Partial<TNew>,
    tx: DbTransaction,
    options?: QueryOptions,
    context?: DomainHookContext<DomainEnvVars>,
  ): Promise<T> {
    // Strip unaccepted fields from input (before any hooks)
    const strippedInput = stripUnacceptedFields(
      input as unknown as Record<string, unknown>,
      this.fields.updateUnacceptedFields,
    );

    // Before-update hook (outside transaction, before validation)
    let transformedInput: unknown = strippedInput;
    if (this.hooks.beforeUpdate) {
      transformedInput = await this.hooks.beforeUpdate(id, strippedInput, context);
    }

    // Validate input before pre-hook (partial update)
    const validatedInput = this.config.updateSchema.parse(transformedInput) as Partial<TNew>;

    // Pre-update hook
    let processedInput = validatedInput;
    if (this.hooks.preUpdate) {
      processedInput = await this.hooks.preUpdate(id, validatedInput, input, tx, context);
      // Validate pre-hook output
      processedInput = this.config.updateSchema.parse(processedInput) as Partial<TNew>;
    }

    // Build update values
    const updateValues: Record<string, unknown> = { ...processedInput };
    if (this.config.hasTimestamps) {
      updateValues.updatedAt = sql\`(extract(epoch from now()) * 1000)::bigint\`;
    }

    // Perform update
    const [updated] = await tx
      .update(this.config.table)
      .set(updateValues)
      .where(eq(this.pkColumn, id))
      .returning() as T[];

    if (!updated) {
      throw new NotFoundException(\`\${this.config.modelName} with id \${id} not found\`);
    }

    // Post-update hook
    let result = updated;
    if (this.hooks.postUpdate) {
      result = await this.hooks.postUpdate(id, processedInput, updated, input, tx, context);
    }

    // Sanitize response unless skipped
    if (!options?.skipSanitization) {
      result = stripUnexposedFields(result, this.fields.readUnexposedFields) as T;
    }

    // After-update hook: starts once the transaction has committed, receives what the caller gets
    if (this.hooks.afterUpdate) {
      const afterUpdate = this.hooks.afterUpdate;
      runAfterCommit(tx, () => afterUpdate(result, input, context));
    }

    return result;
  }

  /**
   * Delete a record
   */
  async delete(
    id: string,
    tx: DbTransaction,
    options?: QueryOptions,
    context?: DomainHookContext<DomainEnvVars>,
  ): Promise<T> {
    // Before-delete hook (outside transaction)
    if (this.hooks.beforeDelete) {
      await this.hooks.beforeDelete(id, context);
    }

    // Pre-delete hook
    if (this.hooks.preDelete) {
      const preResult = await this.hooks.preDelete(id, tx, context);
      id = preResult.id;
    }

    // Perform delete
    const [deleted] = await tx
      .delete(this.config.table)
      .where(eq(this.pkColumn, id))
      .returning() as T[];

    if (!deleted) {
      throw new NotFoundException(\`\${this.config.modelName} with id \${id} not found\`);
    }

    // Post-delete hook
    let result = deleted;
    if (this.hooks.postDelete) {
      result = await this.hooks.postDelete(id, deleted, tx, context);
    }

    // Sanitize response unless skipped
    if (!options?.skipSanitization) {
      result = stripUnexposedFields(result, this.fields.readUnexposedFields) as T;
    }

    // After-delete hook: starts once the transaction has committed, receives what the caller gets
    if (this.hooks.afterDelete) {
      const afterDelete = this.hooks.afterDelete;
      runAfterCommit(tx, () => afterDelete(result, context));
    }

    return result;
  }
}
`;
  }
}
