/**
 * Generates the REST CRUD factory for shared handler logic
 *
 * This generates a factory that creates standard CRUD handlers,
 * reducing boilerplate in individual REST files.
 */
export class RestCrudFactoryGenerator {
  /**
   * Generate the CRUD factory file content
   */
  generate(): string {
    return `/**
 * REST CRUD Factory
 *
 * Provides factory functions to create standard CRUD handlers.
 * Reduces boilerplate across individual REST files.
 *
 * Generated by COG - Do not modify manually
 */

import { Hono, type Context } from '@hono/hono';
import { HTTPException } from '@hono/hono/http-exception';
import { withTransaction, type DbTransaction } from '../db/database.ts';
import { convertBigIntToNumber, handleDomainException, parseJsonBody, parseWhereParam, validateFilter, type FieldMeta } from './helpers.ts';
import { type QueryOptions } from '../domain/hooks.types.ts';

// ============================================
// Types
// ============================================

/**
 * Domain interface that CRUD handlers expect
 * Note: REST layer passes WhereFilter (JSON object), domain converts to SQL internally
 */
export interface CrudDomain<T, TNew> {
  findMany(
    tx: DbTransaction | undefined,
    options?: QueryOptions,
    context?: unknown,
  ): Promise<{ data: T[]; total: number }>;

  findById(
    id: string,
    tx: DbTransaction | undefined,
    options?: QueryOptions,
    context?: unknown,
  ): Promise<T | null>;

  create(
    data: TNew,
    tx: DbTransaction,
    options?: QueryOptions,
    context?: unknown,
  ): Promise<T>;

  update(
    id: string,
    data: Partial<TNew>,
    tx: DbTransaction,
    options?: QueryOptions,
    context?: unknown,
  ): Promise<T>;

  delete(
    id: string,
    tx: DbTransaction,
    options?: QueryOptions,
    context?: unknown,
  ): Promise<T>;
}

/**
 * Configuration for CRUD route generation
 */
export interface CrudConfig<T, TNew> {
  /** The domain instance */
  domain: CrudDomain<T, TNew>;
  /** Field metadata for filter validation */
  fieldMeta: Map<string, FieldMeta>;
  /** Model name for error messages */
  modelName: string;
  /** Endpoint configuration */
  endpoints?: {
    readMany?: boolean;
    readOne?: boolean;
    create?: boolean;
    update?: boolean;
    delete?: boolean;
  };
}

// ============================================
// Factory Functions
// ============================================

/**
 * Create a list (GET /) handler
 */
export const createListHandler = <T, TNew, RestEnvVars extends Record<string, unknown>>(
  config: CrudConfig<T, TNew>,
) => {
  return async (c: Context<{ Variables: RestEnvVars }>) => {
    try {
      const context = c.var as RestEnvVars;
      const { limit = '10', offset = '0', orderBy, orderDirection = 'asc', include, where } = c.req.query();

      // Parse include parameter
      const includeArray = include ? include.split(',') : undefined;

      // Parse and validate filter parameter
      let whereFilter;
      if (where) {
        try {
          whereFilter = parseWhereParam(where);
          if (whereFilter) {
            const validation = validateFilter(whereFilter, config.fieldMeta);
            if (!validation.valid) {
              throw new HTTPException(400, { message: validation.error });
            }
          }
        } catch (error) {
          if (error instanceof HTTPException) throw error;
          throw new HTTPException(400, { message: (error as Error).message });
        }
      }

      const result = await config.domain.findMany(
        undefined,
        {
          where: whereFilter,
          include: includeArray,
          limit: parseInt(limit),
          offset: parseInt(offset),
          orderBy,
          orderDirection: orderDirection as 'asc' | 'desc',
        },
        context,
      );

      return c.json({
        data: convertBigIntToNumber(result.data),
        pagination: {
          total: result.total,
          limit: parseInt(limit),
          offset: parseInt(offset),
        },
      });
    } catch (error) {
      handleDomainException(error);
    }
  };
};

/**
 * Create a get by ID (GET /:id) handler
 */
export const createGetByIdHandler = <T, TNew, RestEnvVars extends Record<string, unknown>>(
  config: CrudConfig<T, TNew>,
) => {
  return async (c: Context<{ Variables: RestEnvVars }, '/:id'>) => {
    try {
      const id = c.req.param('id');
      const context = c.var as RestEnvVars;
      const include = c.req.query('include')?.split(',');

      const result = await config.domain.findById(id, undefined, { include }, context);

      if (!result) {
        throw new HTTPException(404, { message: \`\${config.modelName} not found\` });
      }

      return c.json({ data: convertBigIntToNumber(result) });
    } catch (error) {
      handleDomainException(error);
    }
  };
};

/**
 * Create a create (POST /) handler
 */
export const createCreateHandler = <T, TNew, RestEnvVars extends Record<string, unknown>>(
  config: CrudConfig<T, TNew>,
) => {
  return async (c: Context<{ Variables: RestEnvVars }>) => {
    try {
      const body = await parseJsonBody<TNew>(c);
      const context = c.var as RestEnvVars;

      const result = await withTransaction(async (tx) => {
        return await config.domain.create(body, tx, {}, context);
      });

      return c.json({ data: convertBigIntToNumber(result) }, 201);
    } catch (error) {
      handleDomainException(error);
    }
  };
};

/**
 * Create an update (PUT /:id) handler
 */
export const createUpdateHandler = <T, TNew, RestEnvVars extends Record<string, unknown>>(
  config: CrudConfig<T, TNew>,
) => {
  return async (c: Context<{ Variables: RestEnvVars }, '/:id'>) => {
    try {
      const id = c.req.param('id');
      const body = await parseJsonBody<Partial<TNew>>(c);
      const context = c.var as RestEnvVars;

      const result = await withTransaction(async (tx) => {
        return await config.domain.update(id, body, tx, {}, context);
      });

      return c.json({ data: convertBigIntToNumber(result) });
    } catch (error) {
      handleDomainException(error);
    }
  };
};

/**
 * Create a delete (DELETE /:id) handler
 */
export const createDeleteHandler = <T, TNew, RestEnvVars extends Record<string, unknown>>(
  config: CrudConfig<T, TNew>,
) => {
  return async (c: Context<{ Variables: RestEnvVars }, '/:id'>) => {
    try {
      const id = c.req.param('id');
      const context = c.var as RestEnvVars;

      const result = await withTransaction(async (tx) => {
        return await config.domain.delete(id, tx, {}, context);
      });

      return c.json({ data: convertBigIntToNumber(result) });
    } catch (error) {
      handleDomainException(error);
    }
  };
};

/**
 * Register all CRUD routes on a Hono instance
 */
export const registerCrudRoutes = <T, TNew, RestEnvVars extends Record<string, unknown>>(
  routes: Hono<{ Variables: RestEnvVars }>,
  config: CrudConfig<T, TNew>,
): void => {
  const endpoints = config.endpoints || {};

  if (endpoints.readMany !== false) {
    routes.get('/', createListHandler<T, TNew, RestEnvVars>(config));
  }

  if (endpoints.readOne !== false) {
    routes.get('/:id', createGetByIdHandler<T, TNew, RestEnvVars>(config));
  }

  if (endpoints.create !== false) {
    routes.post('/', createCreateHandler<T, TNew, RestEnvVars>(config));
  }

  if (endpoints.update !== false) {
    routes.put('/:id', createUpdateHandler<T, TNew, RestEnvVars>(config));
  }

  if (endpoints.delete !== false) {
    routes.delete('/:id', createDeleteHandler<T, TNew, RestEnvVars>(config));
  }
};
`;
  }
}
